[project]
name = "SplaTAM"
version = "0.1.0"
description = "Add a short description here"
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "pytorch", "conda-forge"]
platforms = ["linux-64"]

[dependencies]
cuda = {version = "*", channel="nvidia/label/cuda-11.8.0"}
pip = ">=23.3.1,<23.4"
python = "3.10.*"
pytorch = "2.0.1.*"
torchvision = "0.15.2.*"
pytorch-cuda = "11.8.*"
plyfile = ">=1.0.2,<1.1"
rerun-sdk = ">=0.10.1,<0.11"
icecream = ">=2.1.3,<2.2"

[tasks]
nerfstudio-install = "python -m pip install nerfstudio"
fix-ffmpeg = "rm -r .pixi/env/bin/ffmpeg && rm -r .pixi/env/bin/ffprobe"
post-install = { cmd = "pip install -r requirements.txt", depends_on = ["nerfstudio-install"] }